"use client";

import { useState } from "react";
import { useChatContext } from "@/context/ChatContext";

// ── Section parser ─────────────────────────────────────────────────────────
//
// Claude outputs the offer as numbered sections: "1. Heading\ncontent..."
// We split on those boundaries and strip parenthetical descriptions from headings.

type ParsedSection = {
  number: number;
  heading: string;
  content: string;
};

function parseOfferSections(text: string): ParsedSection[] {
  const lines = text.split("\n");
  const sections: ParsedSection[] = [];
  let current: ParsedSection | null = null;
  const contentLines: string[] = [];

  for (const line of lines) {
    const match = line.match(/^(\d+)\.\s+(.+)$/);
    if (match) {
      if (current) {
        current.content = contentLines.splice(0).join("\n").trim();
        sections.push(current);
      }
      const heading = match[2].replace(/\s*\([^)]+\)\s*$/, "").trim();
      current = { number: parseInt(match[1]), heading, content: "" };
    } else if (current) {
      contentLines.push(line);
    }
  }

  if (current) {
    current.content = contentLines.join("\n").trim();
    sections.push(current);
  }

  return sections;
}

// ── Service label map ──────────────────────────────────────────────────────

const SERVICE_LABELS: Record<string, string> = {
  brand_identity: "Brand Identity",
  website_landing: "Website & Landing Pages",
  ai_assistant: "AI Assistant",
  business_automation: "Business Automation",
  offer_messaging: "Offer & Messaging",
  audit_strategy: "Audit & Strategy",
  custom_digital_solution: "Custom Digital Solution",
};

// ── PDF generator ──────────────────────────────────────────────────────────

function printOffer(sections: ParsedSection[], contactName: string) {
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const sectionHtml = sections
    .map((s) => {
      const isMissing = s.number === 4;
      const containerStyle = isMissing
        ? "background:#fff8f0;padding:12px 16px;border-left:3px solid #f59e0b;border-radius:4px;"
        : "";
      return (
        `<div class="section">` +
        `<div class="section-label">${s.heading.toUpperCase()}</div>` +
        `<div class="section-content" style="${containerStyle}">` +
        s.content.replace(/\n/g, "<br>") +
        `</div></div>`
      );
    })
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PIXEL Brief — ${contactName}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      max-width: 680px;
      margin: 48px auto;
      color: #1a1a1a;
      line-height: 1.6;
      font-size: 14px;
    }
    .header { margin-bottom: 40px; border-bottom: 2px solid #e5e5e5; padding-bottom: 20px; }
    .header h1 { font-size: 22px; font-weight: 700; margin: 0 0 4px; }
    .header p { color: #666; font-size: 13px; margin: 0; }
    .section { margin-bottom: 28px; }
    .section-label {
      font-size: 10px;
      font-weight: 700;
      letter-spacing: 0.1em;
      color: #888;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    .section-content { color: #333; }
    .footer {
      margin-top: 48px;
      padding-top: 20px;
      border-top: 1px solid #e5e5e5;
      font-size: 12px;
      color: #999;
    }
    @media print { body { margin: 20px auto; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>PIXEL Brief</h1>
    <p>Prepared by PixelMate · ${date}${contactName ? ` · ${contactName}` : ""}</p>
  </div>
  ${sectionHtml}
  <div class="footer">This brief was generated by PixelMate and is intended for internal PIXEL team review.</div>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  setTimeout(() => win.print(), 400);
}

// ── Section renderers ──────────────────────────────────────────────────────

function SectionHeading({
  children,
  style,
}: {
  children: React.ReactNode;
  style?: React.CSSProperties;
}) {
  return (
    <p
      className="text-xs font-semibold uppercase tracking-wider mb-2"
      style={{ color: "#5C5854", letterSpacing: "0.07em", ...style }}
    >
      {children}
    </p>
  );
}

function Divider() {
  return (
    <div
      className="my-4"
      style={{ height: 1, background: "rgba(255,255,255,0.05)" }}
    />
  );
}

// ── Main component ─────────────────────────────────────────────────────────

export default function OfferCard() {
  const { agentOutputs, contactData, fileSummaries, messages, sessionId, forceState } = useChatContext();
  const offer = agentOutputs.offer;

  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  if (!offer) return null;

  // Deferred tier: simple message, no structured card
  if (offer.tier === "deferred") {
    return (
      <div
        className="rounded-2xl px-5 py-4 text-sm leading-relaxed text-text-secondary"
        style={{
          background: "#18181C",
          border: "1px solid rgba(255,255,255,0.07)",
          marginTop: 4,
        }}
      >
        {offer.text}
      </div>
    );
  }

  const sections = parseOfferSections(offer.text);
  const hasStructuredSections = sections.length >= 3;

  async function handleSend() {
    if (submitting || submitted) return;
    setSubmitting(true);
    setSubmitError(null);

    try {
      // Build the conversationHistory in the format the packager expects
      const conversationHistory = messages
        .filter((m) => m.id !== 0 && !m.streaming)
        .map((m) => ({
          role: (m.role === "bot" ? "assistant" : "user") as "user" | "assistant",
          content: m.text,
        }));

      // ── Step 1: write to CRM + Supabase ─────────────────────────────────
      const writeRes = await fetch("/api/crm/write", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          sessionId,
          contact: contactData ?? {},
          brief: agentOutputs.brief,
          serviceMatches: agentOutputs.services,
          validation: agentOutputs.validation,
          offer,
          fileSummaries,
          conversationHistory,
        }),
      });

      if (!writeRes.ok) {
        const body = await writeRes.json();
        throw new Error(body.error ?? "write_failed");
      }

      const { lead_id: leadId, payload: crmPayload } = await writeRes.json();

      // ── Step 2: notify PIXEL team — fire-and-forget, never blocks UX ────
      fetch("/api/notify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ payload: crmPayload, leadId }),
      }).catch((err) => console.error("[OfferCard] notify failed:", err));

      setSubmitted(true);
      forceState("DONE");
    } catch (err) {
      const msg = err instanceof Error ? err.message : "";
      setSubmitError(
        msg && msg !== "write_failed"
          ? msg
          : "Something went wrong saving your brief. Please try again."
      );
    } finally {
      setSubmitting(false);
    }
  }

  function handleDownload() {
    printOffer(sections, contactData?.name ?? "");
  }

  return (
    <div
      className="rounded-2xl"
      style={{
        background: "#18181C",
        border: "1px solid rgba(200,245,96,0.18)",
        marginTop: 4,
        overflow: "hidden",
      }}
    >
      {/* Card header */}
      <div
        className="px-6 py-4 flex items-center justify-between"
        style={{ borderBottom: "1px solid rgba(255,255,255,0.06)" }}
      >
        <div className="flex items-center gap-2.5">
          <div
            className="h-2 w-2 rounded-full"
            style={{ background: "#C8F560", boxShadow: "0 0 6px rgba(200,245,96,0.6)" }}
          />
          <span className="text-xs font-semibold uppercase tracking-widest" style={{ color: "#9A9590" }}>
            PIXEL Draft Brief
          </span>
        </div>
        <span
          className="text-xs rounded-full px-2.5 py-1 font-medium"
          style={{
            background: offer.tier === "full" ? "rgba(200,245,96,0.1)" : "rgba(255,180,50,0.1)",
            color: offer.tier === "full" ? "#C8F560" : "#FFB432",
          }}
        >
          {offer.tier === "full" ? "Full brief" : "Directions to explore"}
        </span>
      </div>

      {/* Card body */}
      <div className="px-6 py-5 flex flex-col gap-0">
        {hasStructuredSections ? (
          sections.map((section, i) => {
            const isMissing = section.number === 4;
            const isNextStep = section.number === 5;
            const isServices = section.number === 2;

            return (
              <div key={section.number}>
                {i > 0 && <Divider />}

                <SectionHeading style={isMissing ? { color: "#D97706" } : isNextStep ? { color: "#9A9590" } : undefined}>
                  {section.heading}
                </SectionHeading>

                {/* Service pills injected into "Where PIXEL may help" */}
                {isServices && agentOutputs.services?.matches && agentOutputs.services.matches.length > 0 && (
                  <div className="flex flex-wrap gap-1.5 mb-3">
                    {agentOutputs.services.matches
                      .filter((m) => m.confidence >= 0.4)
                      .map((m) => (
                        <span
                          key={m.service}
                          className="rounded-full px-3 py-1 text-xs font-medium"
                          style={{
                            background: "rgba(200,245,96,0.1)",
                            border: "1px solid rgba(200,245,96,0.25)",
                            color: "#C8F560",
                          }}
                        >
                          {SERVICE_LABELS[m.service] ?? m.service}
                        </span>
                      ))}
                  </div>
                )}

                {/* Section content */}
                {isMissing ? (
                  <div
                    className="rounded-lg px-4 py-3 text-sm leading-relaxed"
                    style={{
                      background: "rgba(255,180,50,0.07)",
                      border: "1px solid rgba(255,180,50,0.18)",
                      color: "#E8E4DD",
                    }}
                  >
                    {section.content || "—"}
                  </div>
                ) : (
                  <p
                    className="text-sm leading-relaxed"
                    style={{
                      color: isNextStep ? "#E8E4DD" : "#9A9590",
                      fontWeight: isNextStep ? 500 : undefined,
                    }}
                  >
                    {section.content || "—"}
                  </p>
                )}
              </div>
            );
          })
        ) : (
          // Soft offer or unparseable — render as plain text
          <p className="text-sm leading-relaxed text-text-secondary">{offer.text}</p>
        )}

        <Divider />

        {/* Buttons / confirmation */}
        {submitted ? (
          <div className="flex flex-col gap-3">
            <div className="flex items-center gap-2.5">
              <span
                className="flex h-5 w-5 items-center justify-center rounded-full text-xs font-bold"
                style={{ background: "rgba(200,245,96,0.15)", color: "#C8F560" }}
                aria-hidden="true"
              >
                ✓
              </span>
              <span className="text-sm font-medium text-text-primary">
                Brief sent to the PIXEL team
              </span>
            </div>
            <p className="text-sm text-text-secondary leading-relaxed pl-7">
              Thank you! The PIXEL team will review your brief and reach out soon.
            </p>
          </div>
        ) : (
          <div className="flex flex-col gap-3">
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                onClick={handleSend}
                disabled={submitting}
                className="rounded-full px-4 py-2 text-xs font-medium transition-opacity hover:opacity-85 disabled:opacity-50"
                style={{ background: "#C8F560", color: "#0A0A0C" }}
              >
                {submitting ? "Sending…" : "Send to PIXEL team"}
              </button>

              <button
                type="button"
                onClick={handleDownload}
                className="rounded-full px-4 py-2 text-xs font-medium transition-colors"
                style={{
                  background: "transparent",
                  border: "1px solid rgba(255,255,255,0.12)",
                  color: "#9A9590",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.borderColor = "rgba(255,255,255,0.25)";
                  e.currentTarget.style.color = "#E8E4DD";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.borderColor = "rgba(255,255,255,0.12)";
                  e.currentTarget.style.color = "#9A9590";
                }}
              >
                Download as PDF
              </button>
            </div>

            {submitError && (
              <p className="text-xs" style={{ color: "rgba(255,100,100,0.9)" }}>
                {submitError}
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
